### ISSUE TITLE
Improve the frontend of the cafe website

### ISSUE THREAD

**Issue by Amisha-here** [Amisha-here/Royal-Food-Cafe-Website#1]
Hello Everyone! This was my first attempt at web developement.
Help me with improving the frontend look it would be grateful if you do :)

**Comment by akshaydesai26** [comment]
Great attempt!
Padding at certain places can surely improve the look and give more breathing space to the user.
Text visibility is less at some points (Eg in front of burger image)
Also letters are overflowing at 1-2 places. Shall I work on it? 
If you're up for it, assign it to me!

**Comment by Amisha-here** [comment]
> Great attempt!
> Padding at certain places can surely improve the look and give more breathing space to the user.
> Text visibility is less at some points (Eg in front of burger image)
> Also letters are overflowing at 1-2 places. Shall I work on it?
> If you're up for it, assign it to me!

Yes please, Go ahead

**Comment by saritadc** [comment]
I'd like to work on the looks of the website.  Can I take this up @Amisha-here?

**Comment by satyum** [comment]
HI, can i work on the UI of the website? If you have any idea regarding the interface you can assign me.

**Comment by Amisha-here** [comment]
> I'd like to work on the looks of the website. Can I take this up @Amisha-here?

Yes Sure

**Comment by Amisha-here** [comment]
> HI, can i work on the UI of the website? If you have any idea regarding the interface you can assign me.

Yes that would be great.

**Comment by lakshit123456789** [comment]
> i think i can help you please tell me if i can

i can try my best please tell me
i want to do this work

**Comment by satyum** [comment]
Hey, maybe you should assigned a particular task to everyone or connect with them ,if everyone's gonna commit the same code it can create conflict.

**Comment by CamilaBodack** [comment]
Hi, @Amisha- here. I can help you:). I would like to know what are the priorities and if you allow to adjust colors and other things related to CSS and HTML structure.

**Comment by Amisha-here** [comment]
> Hi, @Amisha- here. I can help you:). I would like to know what are the priorities and if you allow to adjust colors and other things related to CSS and HTML structure.

Yes it would be great if you could change colors and CSS
